/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import constants.Constants;
import javax.swing.JOptionPane;
import taikhoan.TaiKhoanDAO;
import utils.DateTimeUtil;
import vaitro.GiaoVu;
import vaitro.GiaoVuDAO;

/**
 *
 * @author Admin
 */
public class AddOrUpdateGiaoVu extends javax.swing.JFrame {

    /**
     * Creates new form AddOrUpdateGiaoVu
     */
    private int mode;
    private GiaoVu giaoVu;
    private ManagerDashboard managerDashBoard;
    public AddOrUpdateGiaoVu(int mode, int idGv, ManagerDashboard md) {
        if (idGv>0) giaoVu = GiaoVuDAO.timGiaoVu(idGv);
        this.mode = mode;
        this.managerDashBoard=md;
        initComponents();
        if (mode==Constants.UPDATE_MODE) setAvailableData();
    }

    private AddOrUpdateGiaoVu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setAvailableData(){
        hoTenText.setText(giaoVu.getHoTen());
        maGvText.setText(giaoVu.getMaGv());
        sdtText.setText(giaoVu.getSdt());
        diaChiText.setText(giaoVu.getDiaChi());
        if (giaoVu.getGioiTinh().equals("nam")) namBtn.setSelected(true); else nuBtn.setSelected(true);
        ngaySinhPicker.setDate(DateTimeUtil.convertToLocalDateViaSqlDate(giaoVu.getNgaySinh()));
        matKhauText.setText(giaoVu.getTaiKhoan().getMatKhau());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        gioiTinhBtnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        maGvText = new javax.swing.JTextField();
        hoTenText = new javax.swing.JTextField();
        diaChiText = new javax.swing.JTextField();
        sdtText = new javax.swing.JTextField();
        ngaySinhPicker = new com.github.lgooddatepicker.components.DatePicker();
        huyBtn = new javax.swing.JButton();
        xacNhanBtn = new javax.swing.JButton();
        namBtn = new javax.swing.JRadioButton();
        nuBtn = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        matKhauText = new javax.swing.JTextField();
        if (mode == Constants.ADD_MODE) matKhauText.setEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm/Cập nhật");
        setPreferredSize(new java.awt.Dimension(350, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(350, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Mã giáo vụ:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Họ tên:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Địa chỉ:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setText("Số điện thoại:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setText("Ngày sinh:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);

        jLabel6.setText("Giới tính:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        getContentPane().add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        getContentPane().add(maGvText, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        getContentPane().add(hoTenText, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        getContentPane().add(diaChiText, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        getContentPane().add(sdtText, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        getContentPane().add(ngaySinhPicker, gridBagConstraints);

        huyBtn.setText("Hủy bỏ");
        huyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huyBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(huyBtn, gridBagConstraints);

        xacNhanBtn.setText("Xác nhận");
        xacNhanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xacNhanBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 20);
        getContentPane().add(xacNhanBtn, gridBagConstraints);

        gioiTinhBtnGroup.add(namBtn);
        namBtn.setText("nam");
        namBtn.setActionCommand("nam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(namBtn, gridBagConstraints);

        gioiTinhBtnGroup.add(nuBtn);
        nuBtn.setText("nữ");
        nuBtn.setActionCommand("nữ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        getContentPane().add(nuBtn, gridBagConstraints);

        jLabel7.setText("Mật khẩu:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        getContentPane().add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 20);
        getContentPane().add(matKhauText, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void huyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huyBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_huyBtnActionPerformed

    private void xacNhanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xacNhanBtnActionPerformed
        // TODO add your handling code here:
        boolean result = false;
        if (mode == Constants.ADD_MODE) giaoVu = new GiaoVu();
        giaoVu.setMaGv(maGvText.getText());
        giaoVu.setHoTen(hoTenText.getText());
        giaoVu.setDiaChi(diaChiText.getText());
        giaoVu.setSdt(sdtText.getText());
        giaoVu.setNgaySinh(DateTimeUtil.convertToDateViaLocalDate(ngaySinhPicker.getDate()));
        giaoVu.setGioiTinh(gioiTinhBtnGroup.getSelection().getActionCommand());
        if (mode == Constants.UPDATE_MODE){
            TaiKhoanDAO.doiMatKhau(giaoVu.getTaiKhoan().getIdTk(), matKhauText.getText());
            result = GiaoVuDAO.capNhatThongTin(giaoVu);
        }else{
            result = GiaoVuDAO.themGiaoVu(giaoVu)>0;
        }
        if (result) {
            if (mode == Constants.UPDATE_MODE)JOptionPane.showConfirmDialog(null,"Cập nhật thành công",Constants.SUCCESS,JOptionPane.DEFAULT_OPTION);
            else JOptionPane.showConfirmDialog(null,"Tên đăng nhập và mật khẩu mặc định là mã giáo vụ",Constants.SUCCESS,JOptionPane.DEFAULT_OPTION);
            managerDashBoard.updateTable("");
        }else {
            JOptionPane.showConfirmDialog(null,Constants.MISSING_PARAMS,Constants.FAIL,JOptionPane.DEFAULT_OPTION);            
        }       
        this.dispose();
    }//GEN-LAST:event_xacNhanBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrUpdateGiaoVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrUpdateGiaoVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrUpdateGiaoVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrUpdateGiaoVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOrUpdateGiaoVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField diaChiText;
    private javax.swing.ButtonGroup gioiTinhBtnGroup;
    private javax.swing.JTextField hoTenText;
    private javax.swing.JButton huyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField maGvText;
    private javax.swing.JTextField matKhauText;
    private javax.swing.JRadioButton namBtn;
    private com.github.lgooddatepicker.components.DatePicker ngaySinhPicker;
    private javax.swing.JRadioButton nuBtn;
    private javax.swing.JTextField sdtText;
    private javax.swing.JButton xacNhanBtn;
    // End of variables declaration//GEN-END:variables
}
