/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import constants.Constants;
import dkhp.SinhVienHocPhan;
import dkhp.SinhVienHocPhanDAO;
import hocphan.HocPhan;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import utils.DateTimeUtil;
import vaitro.SinhVien;

/**
 *
 * @author Admin
 */
public class DsSvTrongHp extends javax.swing.JFrame {

    /**
     * Creates new form DsSvTrongHp
     */
    private List<SinhVienHocPhan> dsSVHP;
    private HocPhan hocPhan;
    public DsSvTrongHp(HocPhan hp) {
        dsSVHP = SinhVienHocPhanDAO.xemSvTrongHp(hp, "");
        this.hocPhan = hp;
        initComponents();
    }
    public String caHocIntToString(int index){
        return Constants.caHocStrings[index];
    }
    private DsSvTrongHp() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public String[][] mappingDsSVHP(List<SinhVienHocPhan> dsSVHP){
        String[][] result = new String[dsSVHP.size()][Constants.svHpHeader.length];
        for (int i=0;i<dsSVHP.size();i++){
            SinhVienHocPhan svhp = dsSVHP.get(i);
            SinhVien sv = svhp.getSinhVien();
            HocPhan hp = svhp.getHocPhan();
            String[] s={
                sv.getMssv(),sv.getHoTen(),hp.getMaHocPhan(),hocPhan.getMonHoc().getTenMonHoc(),
                hp.getGvLyThuyet(),hp.getNgayHoc(),caHocIntToString(hp.getCaHoc()),
                DateTimeUtil.convertToStringViaDate(svhp.getNgayDangKi())
            };
            result[i]=s;
        }
        return result;
    }
        public void updateSvHpTable(String keyword){
        DefaultTableModel tableModel = (DefaultTableModel) svHpTable.getModel();
        dsSVHP = SinhVienHocPhanDAO.xemSvTrongHp(hocPhan, keyword) ;
        tableModel.setDataVector(mappingDsSVHP(dsSVHP), Constants.svHpHeader);
        tableModel.fireTableDataChanged();   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        timSvText = new javax.swing.JTextField();
        timSvBtn = new javax.swing.JButton();
        svHpScrollpane = new javax.swing.JScrollPane();
        svHpTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Xem sinh viên trong học phần");
        setPreferredSize(new java.awt.Dimension(1000, 300));
        setSize(new java.awt.Dimension(1000, 300));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        timSvText.setText("Tìm tên sinh viên, mã sinh viên, tên học phần, mã học phần");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 100, 0, 500);
        getContentPane().add(timSvText, gridBagConstraints);

        timSvBtn.setText("Tìm kiếm");
        timSvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timSvBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 400);
        getContentPane().add(timSvBtn, gridBagConstraints);

        svHpScrollpane.setColumnHeaderView(svHpTable);
        svHpScrollpane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        svHpScrollpane.setRowHeaderView(svHpTable);
        svHpScrollpane.setViewportView(svHpTable);

        svHpTable.setModel(new DefaultTableModel(mappingDsSVHP(dsSVHP),Constants.svHpHeader));
        svHpScrollpane.setViewportView(svHpTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(svHpScrollpane, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void timSvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timSvBtnActionPerformed
        // TODO add your handling code here:
        String keyword = timSvText.getText();
        updateSvHpTable(keyword);
    }//GEN-LAST:event_timSvBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DsSvTrongHp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DsSvTrongHp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DsSvTrongHp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DsSvTrongHp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DsSvTrongHp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane svHpScrollpane;
    private javax.swing.JTable svHpTable;
    private javax.swing.JButton timSvBtn;
    private javax.swing.JTextField timSvText;
    // End of variables declaration//GEN-END:variables
}
