/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import constants.Constants;
import dkhp.SinhVienHocPhanDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import monhoc.MonHoc;
import vaitro.SinhVien;

/**
 *
 * @author Admin
 */
public class XemMon extends javax.swing.JFrame {

    /**
     * Creates new form XemMon
     */
    private List<MonHoc> dsMonHoc;
    public XemMon(SinhVien sv) {
        dsMonHoc = SinhVienHocPhanDAO.xemMonDaDangKi(sv);
        initComponents();
    }

    private XemMon() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public String[][] mappingDsMonHoc(List<MonHoc> dsMonHoc){
        String[][] result = new String[dsMonHoc.size()][Constants.monHocHeader.length];
        for (int i=0;i<dsMonHoc.size();i++){
            MonHoc t = dsMonHoc.get(i);
            String[] mh={t.getMaMonHoc(),t.getTenMonHoc(),String.valueOf(t.getSoTinChi())};
            result[i]=mh;
        }
        return result;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        xemMonScrollpane = new javax.swing.JScrollPane();
        xemMonTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Môn đã đăng kí");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        xemMonScrollpane.setRowHeaderView(xemMonTable);
        xemMonScrollpane.setViewportView(xemMonTable);

        xemMonTable.setModel(new DefaultTableModel(mappingDsMonHoc(dsMonHoc),Constants.monHocHeader));
        xemMonScrollpane.setViewportView(xemMonTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(xemMonScrollpane, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XemMon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane xemMonScrollpane;
    private javax.swing.JTable xemMonTable;
    // End of variables declaration//GEN-END:variables
}
